# Generated by Django 5.2 on 2025-04-25 21:04

import programs.utils
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='id',
            field=programs.utils.CustomIDField(editable=False, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
